### ISSUE TITLE
Make output path use shell's working directory

### ISSUE THREAD

**Issue by jamesmontalvo3** [jamesmontalvo3/spacewalk#4]
The output path option (`-o`) does not appear to be respecting the user's working directory.

I pulled the STS-134 sample into it's own directory on my desktop for testing purposes:

```
$ pwd
/c/Users/myuser/Desktop/sta-134-eva-not-in-repo
$ ls
egress.yml  main.yml  misse7.yml  WVSRecorders.PNG
```

Then running `eva-checklist -i ./main.yml -o ./test.html` I get:

```
Attach '''GREEN''' hook on S1 HR 3208 (bay 17)
Attach '''GREEN''' hook on S1 HR 3217 or Xo 5790 (bay 17)
'''Translate aft to S3 Face 1 - S3 CETA Light Install'''
Completed! your file is located at file://C:\Users\myuser\AppData\Roaming\npm\node_modules\evachecklist\test.html
```

Note the file output location is not in `/c/Users/myuser/Desktop/sta-134-eva-not-in-repo` even though I specified the path relative to my working directory. It's not putting `test.html` in my shell's working directory. I'm guessing the directory listed is Node's working directory during runtime, perhaps?

**Comment by delacruzjl** [comment]
Fixed

**Comment by jamesmontalvo3** [comment]
Thanks!
