### ISSUE TITLE
Images not displaying due to path relative to output file location

### ISSUE THREAD

**Issue by jamesmontalvo3** [jamesmontalvo3/spacewalk#5]
Images are not showing if my output path is not to the same directory as my input file.

I pulled the STS-134 sample into it's own directory on my desktop for testing purposes:

```
$ pwd
/c/Users/myuser/Desktop/sta-134-eva-not-in-repo
$ ls
egress.yml  main.yml  misse7.yml  WVSRecorders.PNG
```

Then running `eva-checklist -i ./main.yml -o ./test.html` I get:

```
Attach '''GREEN''' hook on S1 HR 3208 (bay 17)
Attach '''GREEN''' hook on S1 HR 3217 or Xo 5790 (bay 17)
'''Translate aft to S3 Face 1 - S3 CETA Light Install'''
Completed! your file is located at file://C:\Users\myuser\AppData\Roaming\npm\node_modules\evachecklist\test.html
```

If I view the `test.html` file in a browser, `WVSRecorders.PNG` does not show. It was initially `WVSRecorders.png` (lowercase extension) in YAML file, so the image filename and the filename in the YAML file did not match, but that is not the issue. Instead the html file is looking for the image relative to wherever you set the output file. So if you set the output file to `/path/to/output/eva.html`, then it's looking for the image at `/path/to/output/someimage.jpg`, but the image file is still only at `/path/to/input/someimage.jpg`.

I think the only options here are either:

1. Make the HTML file reference the location of the input files
2. Copy any images to the output location

I think (2) is the best option due to portability of the files.

**Comment by delacruzjl** [comment]
Fixed

**Comment by jamesmontalvo3** [comment]
Looks good. Thanks!
