### ISSUE TITLE
Which repository should be listed in extension.json

### ISSUE THREAD

**Issue by jamesmontalvo3** [jamesmontalvo3/spacewalk#6]
I think the repository listed in `extension.json` should be changed to `https://github.com/jamesmontalvo3/spacewalk`. Thoughts? Also does this require an update to `https://www.npmjs.com/package/evachecklist`?

**Comment by delacruzjl** [comment]
Yes, the npm publish command takes that from the source it was published from, would you be able to add my account as a contributor to the repository?  If not, would it be possible to send you the commands to publish the final release with the proper parameters.

**Comment by delacruzjl** [comment]
Completed

**Comment by jamesmontalvo3** [comment]
Thanks!
